version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run: echo "yarn install"
      - run: echo "EMPTY TESTS"

  deploy:
    docker:
      - image: circleci/node:12.18.3
    environment:
      CI: false
    steps:
      - checkout
      - run: bash .circleci/git-config.sh
      - run: yarn install
      - run: yarn deploy

workflows:
  test_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
