version: 2.1
jobs:
 build:
  docker:
   - image: circleci/node:12.18.3
  steps:
   - checkout
   - run: npm install
 hello:
  docker:
   - image: circleci/node:12.18.3
  steps:
  - checkout
  - run: echo "hello word"

workflows:
 build_and_hello:
  jobs:
   - build
   - hello
