version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: echo "yarn install"

      - run:
          name: Run tests
          command: echo "EMPTY_TEST"

  deploy:
    docker:
      - image: circleci/node:12.18.3
    environment:
      CI: false # CI as true will consider warning as an error and will stop the deployment
    steps:
      - checkout

      - run:
          name: Configure git
          command: |
            git config --global user.email "mateusfelipefg77@gmail.com"
            git config --global user.name "Mateus Felipe"

      - run:
          name: Install dependencies
          command: yarn install

      - run:
          name: Deploy app
          command: yarn deploy

workflows:
  test_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
