version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run: echo "yarn install"
      - run: echo "EMPTY TESTS"
      - run: exit 1

  deploy:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run: yarn install
      - run: yarn deploy

workflows:
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
