version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run: echo "npm install"
  test:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run: exit 1
  deploy:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run: echo "npm deploy"

workflows:
  build_test_deploy:
    jobs:
      - build
      - test
      - deploy
