version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: echo $YARN_INSTALL

      - run:
          name: Run tests
          command: echo $EMPTY_TEST

  deploy:
    docker:
      - image: circleci/node:12.18.3
    environment:
      CI: false
    steps:
      - checkout

      # - add_ssh_keys:
      #     fingerprints:
      #       - '38:90:63:d3:d8:94:d6:09:ed:7c:d0:9e:95:80:8a:2d'

      - run:
          name: Configure git
          command: bash .circleci/git-config.sh

      - run:
          name: Install dependencies
          command: yarn install

      - run:
          name: Deploy app
          command: yarn deploy

workflows:
  test_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
