version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run: echo "npm build"
      - run: echo "npm test"

  deploy:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run: echo "npm deploy"

workflows:
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only run deploy-via-git job if the build job has completed
          # filters:
          #   branches:
          #     only: master # only run deploy-via-git job on master branch
