name: CI

on: push

jobs:
  lint:
    name: Check Code Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
