name: "[CI] Push Main"

on:
  push:
    branches:
      - main

jobs:
  call-release:
    name: Call release.yml
    uses: mateusfg7/noisekun/.github/workflows/release.yml@main
    secrets: inherit

  call-lint:
    name: Call lint.yml
    uses: mateusfg7/noisekun/.github/workflows/lint.yml@main
