name: "Generate metrics"

on:
  workflow_dispatch:

jobs:
  call-metrics-generator:
    name: Generate pagespeed metrics
    uses: mateusfg7/mfg-b/.github/workflows/pagespeed-metrics.yml@main
    needs: check-changed-files
    secrets: inherit
    with:
      target: https://noisekun.vercel.app
      pwa: true